import { useState } from 'react'
import { Plus } from 'lucide-react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { addHours } from 'date-fns'
import { CalendarBoard } from '../components/CalendarBoard'
import { Button, Field, Modal, PageHead } from '../components/ui'
import { EVENT_LABELS } from '../lib/constants'
import { useAuth } from '../contexts/AuthContext'
import { useToast } from '../contexts/ToastContext'
import { getProfiles, getProjects } from '../services/api'
import { supabase } from '../lib/supabase'
import type { CalendarEvent, EventType } from '../types/domain'
import { isChronological } from '../lib/validation'

export default function CalendarPage(){const {profile,isAdmin}=useAuth();const {toast}=useToast();const qc=useQueryClient();const [modal,setModal]=useState(false);const [selected,setSelected]=useState<CalendarEvent|null>(null);const [form,setForm]=useState<any>({title:'',description:'',event_type:'plan',project_id:'',starts_at:'',ends_at:'',all_day:false,location:'',participants:[]});const {data:projects=[]}=useQuery({queryKey:['projects',isAdmin?'all':profile?.id],queryFn:()=>getProjects(isAdmin?undefined:profile!.id)});const {data:profiles=[]}=useQuery({queryKey:['profiles','calendar'],queryFn:()=>getProfiles(false),enabled:isAdmin});
 const openDate=(date:string)=>{const start=new Date(`${date}T10:00:00`);setForm({title:'',description:'',event_type:'plan',project_id:'',starts_at:toLocal(start),ends_at:toLocal(addHours(start,1)),all_day:false,location:'',participants:[]});setModal(true)}
 async function save(){if(!form.title?.trim()||!form.starts_at)return toast('Укажи название и дату','error');if(!isChronological(form.starts_at,form.ends_at))return toast('Окончание не может быть раньше начала','error');let eventId:string|null=null;try{const {data,error}=await supabase.from('calendar_events').insert({title:form.title.trim(),description:form.description?.trim()||null,event_type:form.event_type,project_id:form.project_id||null,owner_id:profile!.id,created_by:profile!.id,starts_at:new Date(form.starts_at).toISOString(),ends_at:form.ends_at?new Date(form.ends_at).toISOString():null,all_day:form.all_day,location:form.location?.trim()||null}).select('id').single();if(error)throw error;eventId=data.id;if(form.participants?.length){const participants=Array.from(new Set(form.participants)).filter((id:string)=>id!==profile!.id);if(participants.length){const {error:pErr}=await supabase.from('calendar_event_participants').insert(participants.map((id:string)=>({event_id:data.id,profile_id:id})));if(pErr)throw pErr}}toast('Событие добавлено','success');setModal(false);await qc.invalidateQueries({queryKey:['calendar']})}catch(e:any){if(eventId)await supabase.from('calendar_events').delete().eq('id',eventId);toast(e.message||'Не удалось создать событие','error')}}
 return <div className="page"><PageHead eyebrow="Планы компании" title="Календарь" text="Месяц, неделя и день. Нажми на дату, чтобы быстро добавить съёмку, встречу, план или другое событие." actions={<Button onClick={()=>openDate(new Date().toISOString().slice(0,10))}><Plus/> Добавить</Button>}/><CalendarBoard onDateClick={openDate} onEventClick={setSelected}/>{modal&&<Modal title="Добавить событие" onClose={()=>setModal(false)} footer={<><Button kind="secondary" onClick={()=>setModal(false)}>Отмена</Button><Button onClick={()=>void save()}>Сохранить</Button></>}><div className="form-grid"><Field label="Название" full><input className="input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Съёмка нового филиала"/></Field><Field label="Тип"><select className="select" value={form.event_type} onChange={e=>setForm({...form,event_type:e.target.value as EventType})}>{Object.entries(EVENT_LABELS).filter(([k])=>k!=='task'&&k!=='deadline'&&k!=='project').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="Проект"><select className="select" value={form.project_id} onChange={e=>setForm({...form,project_id:e.target.value})}><option value="">Без проекта</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Начало"><input className="input" type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></Field><Field label="Окончание"><input className="input" type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></Field><Field label="Локация" full><input className="input" value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="Адрес / кабинет / ссылка"/></Field><Field label="Описание" full><textarea className="textarea" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field>{isAdmin&&<Field label="Участники" full><div className="grid grid-3">{profiles.map(p=><label className="check-row" key={p.id}><input type="checkbox" checked={form.participants.includes(p.id)} onChange={e=>setForm({...form,participants:e.target.checked?[...form.participants,p.id]:form.participants.filter((x:string)=>x!==p.id)})}/><span className="tiny">{p.full_name}<br/><span className="muted">{p.job_title}</span></span></label>)}</div></Field>}</div></Modal>}{selected&&<Modal title={selected.title} onClose={()=>setSelected(null)}><div className="stack"><div><b>Тип:</b> {EVENT_LABELS[selected.event_type]}</div><div><b>Начало:</b> {new Date(selected.starts_at).toLocaleString('ru-RU')}</div>{selected.ends_at&&<div><b>Окончание:</b> {new Date(selected.ends_at).toLocaleString('ru-RU')}</div>}{selected.location&&<div><b>Локация:</b> {selected.location}</div>}{selected.description&&<div className="notice-box">{selected.description}</div>}</div></Modal>}</div>}
function toLocal(d:Date){const pad=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
