import { useState } from 'react'
import { Plus, Paperclip } from 'lucide-react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { format } from 'date-fns'
import { useAuth } from '../contexts/AuthContext'
import { useToast } from '../contexts/ToastContext'
import { getProjects, getWorkLogs } from '../services/api'
import { supabase } from '../lib/supabase'
import { WORK_TYPES } from '../lib/constants'
import { Button, Card, Empty, Field, Modal, PageHead, SectionTitle } from '../components/ui'
import { StorageLink } from '../components/StorageLink'
import { dateRu } from '../lib/format'
import { normalizeHttpUrl, uploadError } from '../lib/validation'

export default function WorkLogsPage(){const {profile}=useAuth();const {toast}=useToast();const qc=useQueryClient();const [form,setForm]=useState<any|null>(null);const [file,setFile]=useState<File|null>(null);const {data:logs=[]}=useQuery({queryKey:['work-logs',profile!.id],queryFn:()=>getWorkLogs(profile!.id)});const {data:projects=[]}=useQuery({queryKey:['projects',profile!.id],queryFn:()=>getProjects(profile!.id)});
 async function save(){if(!form?.description?.trim()||!form.work_type)return toast('Укажи тип и описание работы','error');if(!form?.work_date)return toast('Укажи дату работы','error');const minutesRaw=String(form.minutes_spent??'').trim();const minutes=minutesRaw?Number(minutesRaw):null;if(minutes!==null&&(!Number.isFinite(minutes)||minutes<0))return toast('Время должно быть 0 или больше','error');try{const fileProblem=uploadError(file);if(fileProblem)throw new Error(fileProblem);const rawLink=String(form.link||'').trim();const link=rawLink?normalizeHttpUrl(rawLink):null;if(rawLink&&!link)throw new Error('Укажи корректную http/https ссылку');let path:null|string=null;if(file){path=`${profile!.id}/${Date.now()}-${file.name.replace(/[^\w.-]/g,'_')}`;const {error:u}=await supabase.storage.from('work-files').upload(path,file);if(u)throw u}const {error}=await supabase.from('work_logs').insert({profile_id:profile!.id,project_id:form.project_id||null,work_date:form.work_date,work_type:form.work_type,description:form.description.trim(),link,file_path:path,minutes_spent:minutes});if(error){if(path)await supabase.storage.from('work-files').remove([path]);throw error}toast('Работа добавлена в отчёт','success');setForm(null);setFile(null);await qc.invalidateQueries({queryKey:['work-logs']})}catch(e:any){toast(e.message,'error')}}
 return <div className="page"><PageHead eyebrow="История работы" title="Мои работы" text="Фиксируй выполненную работу — эти записи автоматически попадут в месячный отчёт." actions={<Button onClick={()=>setForm({work_date:format(new Date(),'yyyy-MM-dd'),project_id:'',work_type:'',description:'',link:'',minutes_spent:''})}><Plus/> Добавить работу</Button>}/><Card><SectionTitle title="Рабочие записи"/>{logs.length?<div className="timeline">{logs.map(l=><div className="timeline-item" key={l.id}><strong>{dateRu(l.work_date)} · {l.work_type} · {l.project?.name||'Без проекта'}</strong><small>{l.description}{l.minutes_spent?` · ${l.minutes_spent} мин.`:''}</small><div className="row-actions">{l.link&&normalizeHttpUrl(l.link)&&<a href={normalizeHttpUrl(l.link)!} className="link-btn" target="_blank" rel="noreferrer">Открыть ссылку</a>}{l.file_path&&<StorageLink bucket="work-files" path={l.file_path} label="Файл"/>}</div></div>)}</div>:<Empty title="Рабочих записей пока нет"/>}</Card>{form&&<Modal title="Добавить выполненную работу" onClose={()=>setForm(null)} footer={<><Button kind="secondary" onClick={()=>setForm(null)}>Отмена</Button><Button onClick={()=>void save()}>Сохранить</Button></>}><div className="form-grid"><Field label="Дата"><input className="input" type="date" value={form.work_date} onChange={e=>setForm({...form,work_date:e.target.value})}/></Field><Field label="Проект"><select className="select" value={form.project_id} onChange={e=>setForm({...form,project_id:e.target.value})}><option value="">Без проекта</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Тип работы"><select className="select" value={form.work_type} onChange={e=>setForm({...form,work_type:e.target.value})}><option value="">Выбрать</option>{WORK_TYPES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Затраченное время, минут"><input className="input" type="number" min="0" value={form.minutes_spent} onChange={e=>setForm({...form,minutes_spent:e.target.value})}/></Field><Field label="Описание" full><textarea className="textarea" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Сняли два ролика для нового филиала"/></Field><Field label="Ссылка" full><input className="input" value={form.link} onChange={e=>setForm({...form,link:e.target.value})}/></Field><Field label="Файл" full><input className="input" type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></Field></div><div className="notice-box"><Paperclip size={13}/> Файлы хранятся в Supabase Storage и защищены политиками доступа.</div></Modal>}</div>}
